In [1]:
# Loading the Data
import pandas as pd
import numpy as np
df = pd.read_csv(r'anime.csv')
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [2]:
df.loc[3]['Title'] #4th row see

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [3]:
def Extract_episode(txt):
    check = False
    data = ""
    for i in txt:
        if i=="(":
            check = True
        if check == True:
            data += i
        if i==")":
            check = False

    return int(data.replace("(","").replace("eps)",""))
print(Extract_episode('Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'))

51

In [4]:
df["Episodes"] = df["Title"].apply(Extract_episode)
# df2.drop("Disignation",axis =1,inplace=True)
df

    Rank                                              Title  Score  Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04        51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04         1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04       148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04        13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03        13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03         2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02       110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99        13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99        13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98        12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94       201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94         1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93        22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93        24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91        25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91         1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89         1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88         7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88        14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87        74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84         1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84         1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83        12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83         1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82        24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82        23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81        12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81        26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80        13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80        16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79        11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79         1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79        11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78        10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78         1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77        26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77        12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76        75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75        26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75        26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74        24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73        10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72        12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71        12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71         4

- Make a new column for time stamp

In [5]:
df.loc[0]["Title"]

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [6]:
def extraction_time(txt):
    check = False
    T_given = ""
    count = 0

    for i in txt:
        if i == ")":
            check = True
            continue

        if check and count < 19:
            T_given += i
            count += 1

        if count == 19:
            break

    return T_given

print(extraction_time(
    'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'
))

Apr 2015 - Mar 2016

In [7]:
df["Time_stamp"] = df["Title"].apply(extraction_time)
df

,Rank,Title,Score,Episodes,Time_stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

#Extract the Months

In [8]:
# Start Month nikalna (e.g., 'Apr')
df['start_month'] = df['Time_stamp'].str.extract(r'^([A-Za-z]+)')

# End Month nikalna (e.g., 'Jul')
df['end_month'] = df['Time_stamp'].str.extract(r'-\s*([A-Za-z]+)')
df

,Rank,Title,Score,Episodes,Time_stamp,start_month,end_month
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,Apr,Jul
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,Apr,Sep
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,Oct,Dec
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,Apr,Mar
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,Apr,Jul
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,Apr,Mar
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,Jan,Jan
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,Oct,Sep
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,Apr,Jun
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,Oct,Mar
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,Mar,May
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,Jan,Mar
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,Jul,Aug
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,Apr,Jun
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,Jan,Mar
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,Apr,Mar
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,Sep,Sep
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,Oct,Mar
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,Oct,Mar
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,Apr,Sep
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,Jul,Jul
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,Sep,Sep
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,Aug,Aug
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,Jul,Oct
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,Apr,Sep
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,Aug,Aug
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,Dec,Dec
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,Oct,Dec
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,Dec,Dec
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,Jan,Jun
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,Jul,Aug
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,Jan,Mar
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,Apr,Oct
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,Jan,Apr
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,Dec,Mar
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,Dec,Feb
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,Jan,Jan
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,Apr,Jun
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,Oct,Dec
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,Jul,Jul
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,Jul,Dec
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,Jan,Apr
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,Oct,Mar
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,Apr,Apr
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,Apr,Oct
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,Jul,Dec
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,Oct,Dec
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,Jan,Mar
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,Oct,Dec
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,Feb,Sep

### Total Months

In [9]:


# 1. Start aur End date strings ko alag karein
df[['start_str', 'end_str']] = df['Time_stamp'].str.split(' - ', expand=True)

# 2. Dono ko datetime me convert karein
df['start_date'] = pd.to_datetime(df['start_str'].str.strip(), format='%b %Y')
df['end_date'] = pd.to_datetime(df['end_str'].str.strip(), format='%b %Y')

# 3. Total months calculate karein
# Formula: (Year Difference * 12) + Month Difference
df['total_months'] = (df['end_date'].dt.year - df['start_date'].dt.year) * 12 + (df['end_date'].dt.month - df['start_date'].dt.month)

# Agar both months inclusive chahiye (jaise Apr 2009 se Jul 2010 = 16 months inclusive):
# df['total_months'] = df['total_months'] + 1

# Temporary columns drop karne ke liye:
df = df.drop(columns=['start_str', 'end_str'])
df

,Rank,Title,Score,Episodes,Time_stamp,start_month,end_month,start_date,end_date,total_months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,Apr,Jul,2009-04-01,2010-07-01,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,Apr,Sep,2011-04-01,2011-09-01,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,Oct,Dec,2022-10-01,2022-12-01,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,Apr,Mar,2015-04-01,2016-03-01,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,Apr,Jul,2019-04-01,2019-07-01,3
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,Apr,Mar,2011-04-01,2012-03-01,11
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,Jan,Jan,2021-01-01,2021-01-01,0
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,Oct,Sep,2011-10-01,2014-09-01,35
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,Apr,Jun,2022-04-01,2022-06-01,2
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,Oct,Mar,2012-10-01,2013-03-01,5
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,Mar,May,2023-03-01,2023-05-01,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,Jan,Mar,1988-01-01,1997-03-01,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,Jul,Aug,2023-07-01,2023-08-01,1
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,Apr,Jun,2021-04-01,2021-06-01,2
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,Jan,Mar,2017-01-01,2017-03-01,2
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,Apr,Mar,2006-04-01,2010-03-01,47
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,Sep,Sep,2016-09-01,2016-09-01,0
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,Oct,Mar,2017-10-01,2018-03-01,5
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,Oct,Mar,2008-10-01,2009-03-01,5
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,Apr,Sep,2008-04-01,2008-09-01,5
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,Jul,Jul,2013-07-01,2013-07-01,0
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,Sep,Sep,2020-09-01,2020-09-01,0
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,Aug,Aug,2017-08-01,2017-08-01,0
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,Jul,Oct,2018-07-01,2018-10-01,3
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,Apr,Sep,2004-04-01,2005-09-01,17
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,Aug,Aug,2016-08-01,2016-08-01,0
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,Dec,Dec,2022-12-01,2022-12-01,0
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,Oct,Dec,2022-10-01,2022-12-01,2
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,Dec,Dec,2022-12-01,2022-12-01,0
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,Jan,Jun,2023-01-01,2023-06-01,5
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,Jul,Aug,2023-07-01,2023-08-01,1
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,Jan,Mar,2018-01-01,2018-03-01,2
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,Apr,Oct,2020-04-01,2021-10-01,18
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,Jan,Apr,2019-01-01,2019-04-01,3
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,Dec,Mar,2020-12-01,2021-03-01,3
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,Dec,Feb,2021-12-01,2022-02-01,2
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,Jan,Jan,2017-01-01,2017-01-01,0
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,Apr,Jun,2023-04-01,2023-06-01,2
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,Oct,Dec,2016-10-01,2016-12-01,2
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,Jul,Jul,2001-07-01,2001-07-01,0
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,Jul,Dec,2013-07-01,2013-12-01,5
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,Jan,Apr,2022-01-01,2022-04-01,3
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,Oct,Mar,2000-10-01,2002-03-01,17
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,Apr,Apr,1998-04-01,1999-04-01,12
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,Apr,Oct,2022-04-01,2022-10-01,6
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,Jul,Dec,2019-07-01,2019-12-01,5
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,Oct,Dec,2014-10-01,2014-12-01,2
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,Jan,Mar,2017-01-01,2017-03-01,2
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,Oct,Dec,2022-10-01,2022-12-01,2
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,Feb,Sep,1999-02-01,1999-09-01,7

In [10]:
df

,Rank,Title,Score,Episodes,Time_stamp,start_month,end_month,start_date,end_date,total_months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,Apr,Jul,2009-04-01,2010-07-01,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,Apr,Sep,2011-04-01,2011-09-01,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,Oct,Dec,2022-10-01,2022-12-01,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,Apr,Mar,2015-04-01,2016-03-01,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,Apr,Jul,2019-04-01,2019-07-01,3
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,Apr,Mar,2011-04-01,2012-03-01,11
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,Jan,Jan,2021-01-01,2021-01-01,0
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,Oct,Sep,2011-10-01,2014-09-01,35
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,Apr,Jun,2022-04-01,2022-06-01,2
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,Oct,Mar,2012-10-01,2013-03-01,5
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,Mar,May,2023-03-01,2023-05-01,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,Jan,Mar,1988-01-01,1997-03-01,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,Jul,Aug,2023-07-01,2023-08-01,1
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,Apr,Jun,2021-04-01,2021-06-01,2
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,Jan,Mar,2017-01-01,2017-03-01,2
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,Apr,Mar,2006-04-01,2010-03-01,47
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,Sep,Sep,2016-09-01,2016-09-01,0
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,Oct,Mar,2017-10-01,2018-03-01,5
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,Oct,Mar,2008-10-01,2009-03-01,5
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,Apr,Sep,2008-04-01,2008-09-01,5
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,Jul,Jul,2013-07-01,2013-07-01,0
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,Sep,Sep,2020-09-01,2020-09-01,0
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,Aug,Aug,2017-08-01,2017-08-01,0
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,Jul,Oct,2018-07-01,2018-10-01,3
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,Apr,Sep,2004-04-01,2005-09-01,17
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,Aug,Aug,2016-08-01,2016-08-01,0
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,Dec,Dec,2022-12-01,2022-12-01,0
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,Oct,Dec,2022-10-01,2022-12-01,2
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,Dec,Dec,2022-12-01,2022-12-01,0
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,Jan,Jun,2023-01-01,2023-06-01,5
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,Jul,Aug,2023-07-01,2023-08-01,1
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,Jan,Mar,2018-01-01,2018-03-01,2
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,Apr,Oct,2020-04-01,2021-10-01,18
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,Jan,Apr,2019-01-01,2019-04-01,3
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,Dec,Mar,2020-12-01,2021-03-01,3
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,Dec,Feb,2021-12-01,2022-02-01,2
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,Jan,Jan,2017-01-01,2017-01-01,0
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,Apr,Jun,2023-04-01,2023-06-01,2
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,Oct,Dec,2016-10-01,2016-12-01,2
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,Jul,Jul,2001-07-01,2001-07-01,0
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,Jul,Dec,2013-07-01,2013-12-01,5
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,Jan,Apr,2022-01-01,2022-04-01,3
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,Oct,Mar,2000-10-01,2002-03-01,17
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,Apr,Apr,1998-04-01,1999-04-01,12
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,Apr,Oct,2022-04-01,2022-10-01,6
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,Jul,Dec,2019-07-01,2019-12-01,5
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,Oct,Dec,2014-10-01,2014-12-01,2
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,Jan,Mar,2017-01-01,2017-03-01,2
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,Oct,Dec,2022-10-01,2022-12-01,2
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,Feb,Sep,1999-02-01,1999-09-01,7

### Questions to Solve
* which anime has the highest score
* give me top 5 highest scoring anime
* which anime has the highest episode count
* animes with top 5 episode count
* which is the longest running anime

In [11]:
df[(df["Score"]==max(df["Score"]))]["Title"]

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

Sort by No. of Episode

In [12]:
df.sort_values("Episodes", ascending=False)[["Title", "Episodes"]].head(5)

                                                Title  Episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201
7   Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...       148
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...       110
42  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...        75
24  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...        74

In [13]:
# Another way to find the Anime having heigest Score
df.sort_values("Score",ascending=False).head(5)[["Title","Score"]]

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [14]:
# Longest Running time animes
df.sort_values("total_months",ascending=False).iloc[0] #.loc[["0"]] selects the row whose index label is "0"; .iloc[[0]] selects the first row by position.

Rank                                                           12
Title           Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
Score                                                        9.02
Episodes                                                      110
Time_stamp                                    Jan 1988 - Mar 1997
start_month                                                   Jan
end_month                                                     Mar
start_date                                    1988-01-01 00:00:00
end_date                                      1997-03-01 00:00:00
total_months                                                  110
Name: 11, dtype: object

In [15]:
# top 5 scoring
df["Title"].head(5)

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str