# Merging Joining Concatination
        - jab bhi 2 column/rows/data do usko list me rkho
        # Pandas DataFrame Combination: Quick Revision Notes

1. **`pd.merge(df1, df2, on='key', how='...')`**: Combines two DataFrames horizontally based on shared key columns.
2. **Inner Merge (`how='inner'`)**: Keeps only matching rows with keys present in both DataFrames.
3. **Outer Merge (`how='outer'`)**: Keeps all rows from both DataFrames, filling unmatched values with `NaN`.
4. **Left Merge (`how='left'`)**: Retains all rows from the left DataFrame and brings matching data from the right.
5. **Right Merge (`how='right'`)**: Retains all rows from the right DataFrame and brings matching data from the left.
6. **`pd.concat([df1, df2], axis=0)`**: Stacks DataFrames vertically (row-wise) by default.
7. **`pd.concat([df1, df2], axis=1)`**: Appends DataFrames horizontally (column-wise) along rows.
8. **`df1.join(df2, how='...')`**: Combines DataFrames primarily on their index labels (defaults to a left join).

In [18]:
import numpy as np 
import pandas as pd

* Merging 2 dataframe

In [19]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [20]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [21]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [22]:
pd.merge(employees,salaries, on='employee_id') # how='inner' is default , on is also default if not given

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [25]:
pd.merge(employees,salaries, on='employee_id',how = 'outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [26]:
pd.merge(employees,salaries,on='employee_id',how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [27]:
pd.merge(employees,salaries,on='employee_id',how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

Concatination of 2 dataframes

In [52]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [32]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [33]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
JODO = pd.concat([df1,df2])  # column wise
print(JODO)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [36]:
Hodo = pd.concat([df1,df2],axis = 1) # row wise
print(Hodo)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining 2 data freames

In [ ]:
df_1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df_2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [49]:
df_1

      name
1    Alice
2      Bob
3  Charlie

In [46]:
df_2

   score
2     85
3     90
4     75

In [51]:
df_1.join(df_2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [54]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [55]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [57]:
df1.join(df2, how='inner', lsuffix='_df1', rsuffix='_df2')

  A_df1 B_df1 C_df1 A_df2 B_df2 C_df2
0    A0    B0    C0    A3    B3    C3
1    A1    B1    C1    A4    B4    C4
2    A2    B2    C2    A5    B5    C5