# Finding Missing Data
        - Search = isna = row wise
        - remove = dropna = row wise
        - fill = fillna = coulmn wise
        - selection = column wise
        - column wise mean
        - Make it work in Main data frame = inplace= True

In [28]:
import numpy as np 
import pandas as pd 


data = {
    'A': [1, 2, np.nan, 4, 5], # not a number value(None)
    'Ram': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
print(df)

     A  Ram    C    D
0  1.0    1  1.0  1.0
1  2.0    2  2.0  NaN
2  NaN    3  3.0  NaN
3  4.0    4  NaN  NaN
4  5.0    5  NaN  5.0

In [29]:
df.isna().sum() # null value to True # find total no. of null row wise

A      1
Ram    0
C      2
D      3
dtype: int64

In [30]:
df.isna().any() # does it have any row which have null value

A       True
Ram    False
C       True
D       True
dtype: bool

- Remove Null value or missing Data

In [31]:
df.dropna() # remove all row which have null value

     A  Ram    C    D
0  1.0    1  1.0  1.0

In [32]:
df

     A  Ram    C    D
0  1.0    1  1.0  1.0
1  2.0    2  2.0  NaN
2  NaN    3  3.0  NaN
3  4.0    4  NaN  NaN
4  5.0    5  NaN  5.0

In [33]:
df.dropna(thresh=3) # At least have 3 non - null values in rows

     A  Ram    C    D
0  1.0    1  1.0  1.0
1  2.0    2  2.0  NaN
4  5.0    5  NaN  5.0

### Filling all the missing Value

In [34]:
df.fillna(0) # fill na = column wise selection

     A  Ram    C    D
0  1.0    1  1.0  1.0
1  2.0    2  2.0  0.0
2  0.0    3  3.0  0.0
3  4.0    4  0.0  0.0
4  5.0    5  0.0  5.0

In [ ]:
values = {"A":0,"Ram":100,"C":200,"D":400} # column wise 
df.fillna(values)

     A  Ram      C      D
0  1.0    1    1.0    1.0
1  2.0    2    2.0  400.0
2  0.0    3    3.0  400.0
3  4.0    4  200.0  400.0
4  5.0    5  200.0    5.0

- Fill with Mean on missing value

In [38]:
df

     A  Ram    C    D
0  1.0    1  1.0  1.0
1  2.0    2  2.0  NaN
2  NaN    3  3.0  NaN
3  4.0    4  NaN  NaN
4  5.0    5  NaN  5.0

In [ ]:
df.fillna(df.mean()) # column wise mean

     A  Ram    C    D
0  1.0    1  1.0  1.0
1  2.0    2  2.0  3.0
2  3.0    3  3.0  3.0
3  4.0    4  2.0  3.0
4  5.0    5  2.0  5.0