# DATA FRAM
* IS A COLLECTION OF SERIES CONTAINING MULTIPLE COLUMNS

In [60]:
import numpy as np
import pandas as pd

## Data Frame from Dict

In [61]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
d  = pd.Series(data=data)
print(d,sep ="\n") # sep does not work in pandas data frame

Name             [John, Anna, Peter, Linda]
Age                        [28, 34, 29, 42]
City      [New York, Paris, Berlin, London]
Salary         [65000, 70000, 62000, 85000]
dtype: object

In [91]:
df = pd.DataFrame(data=data)
print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [63]:
# If you specifically want TAB-separated output
# Use:

print(df.to_csv(sep="\t", index=False))

Name	Age	City	Salary
John	28	New York	65000
Anna	34	Paris	70000
Peter	29	Berlin	62000
Linda	42	London	85000

In [64]:
print(df.to_string(index=False)) # alingment from left

 Name  Age     City  Salary
 John   28 New York   65000
 Anna   34    Paris   70000
Peter   29   Berlin   62000
Linda   42   London   85000

## Data Frame from List

In [69]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=columns,index= ["a","b","c","d"]) # horizontal(column name) is manual # index is also manual
df2

    Name  Age      City  Salary
a   John   28  New York   65000
b   Anna   34     Paris   70000
c  Peter   29    Berlin   62000
d  Linda   42    London   85000

# Column Selecting

In [70]:
df2["Name"] # for targeting we should give column name (no index)
df2[["Name","City"]] # using Lsit of List

    Name      City
a   John  New York
b   Anna     Paris
c  Peter    Berlin
d  Linda    London

In [ ]:
# adding column
df2["Designation"] = ["Doctor","Eng","Teacher","chor"] # must be same no. element in list
df2   # Important: if we given new name to column to change previous name its does not chnage and make another column

    Name  Age      City  Salary Designation Disignation
a   John   28  New York   65000      Doctor      Doctor
b   Anna   34     Paris   70000         Eng         Eng
c  Peter   29    Berlin   62000     Teacher     Teacher
d  Linda   42    London   85000        chor        chor

* Remove Column

In [79]:
df2.drop("Disignation",axis= 1)

    Name  Age      City  Salary Designation
a   John   28  New York   65000      Doctor
b   Anna   34     Paris   70000         Eng
c  Peter   29    Berlin   62000     Teacher
d  Linda   42    London   85000        chor

In [80]:
df2   # Diginnation does not remove from main data frame 
# to remove from main data use key= "inplace"=True

    Name  Age      City  Salary Designation Disignation
a   John   28  New York   65000      Doctor      Doctor
b   Anna   34     Paris   70000         Eng         Eng
c  Peter   29    Berlin   62000     Teacher     Teacher
d  Linda   42    London   85000        chor        chor

In [81]:
df2.drop("Disignation",axis =1,inplace=True)
df2  # once you remove any column and twice run the code it will not work as it is already deleted and no such column name exist

    Name  Age      City  Salary Designation
a   John   28  New York   65000      Doctor
b   Anna   34     Paris   70000         Eng
c  Peter   29    Berlin   62000     Teacher
d  Linda   42    London   85000        chor

* Multiple column remove

In [132]:
df2.drop(["City","Salary"],axis=1)

    Name  Age Designation
a   John   28      Doctor
b   Anna   34         Eng
c  Peter   29     Teacher
d  Linda   42        chor

Removing Rows

In [86]:
df2.drop(["a","b"],axis=0) # also can use inplace to remove rom main data base , currenty only show how will it look after delition

    Name  Age    City  Salary Designation
c  Peter   29  Berlin   62000     Teacher
d  Linda   42  London   85000        chor

In [85]:
df2

    Name  Age      City  Salary Designation
a   John   28  New York   65000      Doctor
b   Anna   34     Paris   70000         Eng
c  Peter   29    Berlin   62000     Teacher
d  Linda   42    London   85000        chor

## Selecting Row

In [100]:
df2
df2.loc["a"]  # give lable
df2.iloc[1]  # from index use iloc= index location

Name            Anna
Age               34
City           Paris
Salary         70000
Designation      Eng
Name: b, dtype: object

## Selecting rows and Column simultanius

In [109]:
# df2.loc[["a","b"]][["City","Salary"]]
df2.loc["a":"b", ["City", "Salary"]] # "a":"b" → select rows from index a to b ["City", "Salary"] → select these two columns""

       City  Salary
a  New York   65000
b     Paris   70000

In [120]:
df2[["City","Salary"]].loc[["a","b"]]

       City  Salary
a  New York   65000
b     Paris   70000

## Conditional Seleection

In [ ]:
df2
# Now i only want to see whose age is above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary Designation
b   Anna   34   Paris   70000         Eng
d  Linda   42  London   85000        chor

In [131]:
#I only want poeple whose age is above 30 and their city must be paris
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')] # use &

   Name  Age   City  Salary Designation
b  Anna   34  Paris   70000         Eng